config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'recipes#index'

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :description, :ingredients, :directions, presence: true

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo,  content_type: /\Aimage\/.*\z/

  has_many :ingredients, dependent: :destroy
  has_many :directions, dependent: :destroy

  accepts_nested_attributes_for  :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  accepts_nested_attributes_for  :directions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to root_path
    else
      redirect_to @recipe
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :quantity, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RecipeBox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/recipes/_direction_fields.haml
.nested-fields
  = f.input :step, input_html: { class: "form-input form-control" }
  = link_to_remove_association 'Remove', f

app/views/recipes/_form.haml
=simple_form_for @recipe do |f|
  =f.input :title
  =f.input :description
  =f.input :photo, as: :file

  %h3 Ingredients
  #ingredients
    = f.simple_fields_for :ingredients do |ingredient|
      = render 'ingredient_fields', f: ingredient
    .links
      = link_to_add_association 'Add ingredient', f, :ingredients

  %h3 Directions
  #directions
    = f.simple_fields_for :directions do |direction|
      = render 'direction_fields', f: direction
    .links
      = link_to_add_association 'Add direction', f, :directions

  =f.button :submit

app/views/recipes/_ingredient_fields.haml
.nested-fields
  = f.input :name, input_html: { class: "form-input form-control" }
  = f.input :quantity, input_html: { class: "form-input form-control" }
  = link_to_remove_association 'Remove', f

app/views/recipes/edit.haml
%h2
  Edit recipe
=render 'form'

app/views/recipes/index.haml
=link_to "New recipe", new_recipe_path
<br>

-@recipes.each do |recipe|
  =link_to recipe do
    -if recipe.photo.exists?
      =image_tag recipe.photo.url(:medium)
    -else
      =image_tag("image.jpg", size:"300x300")
  %h2
    =recipe.title
  %div
    =recipe.description

app/views/recipes/new.haml
%h2
  New recipe
=render 'form'

app/views/recipes/show.haml
-if @recipe.photo.exists?
  =image_tag @recipe.photo.url(:medium)
-else
  =image_tag("image.jpg", size:"300x300")
%h2
  =@recipe.title
%p
  =@recipe.description
%h4
  Ingredients:
-@recipe.ingredients.each do |ingredient|
  %p
    =ingredient.quantity
    =ingredient.name
%h4
  Directions:
%ol
  -@recipe.directions.each do |direction|
    %li
      =direction.step
%button
  =link_to "edit", edit_recipe_path(@recipe)
%button
  =link_to "delete", recipe_path(@recipe), method: :delete, data: {:confirm => 'Are you sure?'}